In [1]:
# Packages needed:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load dataset
df = pd.read_csv("dataset-umkm-edit.csv")
df

,id_umkm,nama_usaha,jenis_usaha,tenaga_kerja_perempuan,tenaga_kerja_laki_laki,aset,omset,marketplace,kapasitas_produksi,status_legalitas,tahun_berdiri,laba,biaya_karyawan,jumlah_pelanggan
0,28828567.0,UD. Alif Pamungkas,Kesehatan,1.0,56.0,5497149.0,3347794.0,Tokopedia,479.0,Belum Terdaftar,2015.0,-2149355.0,171000000.0,479.0
1,28828568.0,UD. Zidanar Panji,Perdagangan,5.0,44.0,7398384.0,39969661.0,Bukalapak,464.0,Terdaftar,2014.0,32571277.0,147000000.0,464.0
2,28828569.0,UD. Winda Jayengprana,NaN,74.0,51.0,8881762.0,25253355.0,Website Sendiri,383.0,Belum Terdaftar,2000.0,16371593.0,375000000.0,383.0
3,28828570.0,UD. Damaris Satria,Jasa,89.0,5.0,9576178.0,20700389.0,Website Sendiri,986.0,Belum Terdaftar,2003.0,11124211.0,282000000.0,986.0
4,28828571.0,UD. Qasya Wiratama,Jasa,91.0,59.0,9456853.0,4820810.0,Lazada,314.0,Belum Terdaftar,2002.0,-4636043.0,450000000.0,314.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13559,288222126.0,UD. Syana Ilir Rian,Jasa,62.0,63.0,6854562.0,48239150.0,Website Sendiri,162.0,Belum Terdaftar,2003.0,41384588.0,375000000.0,162.0
13560,288222127.0,UD. Bela Widhi,Pendidikan,70.0,50.0,804787.0,35210634.0,Website Sendiri,180.0,Terdaftar,2012.0,34405847.0,360000000.0,180.0
13561,288222128.0,UD. Bayu Alam,Kesehatan,50.0,37.0,8211715.0,8874364.0,Lazada,802.0,Terdaftar,2009.0,662649.0,261000000.0,802.0
13562,288222129.0,UD. Olla Sudharmo Udin,Pendidikan,11.0,NaN,6217989.0,41510653.0,Website Sendiri,122.0,Belum Terdaftar,2009.0,35292664.0,132000000.0,122.0
13563,288222130.0,UD. Qasya Kencana,Pendidikan,57.0,NaN,4523299.0,49813771.0,Shopee,136.0,Terdaftar,2002.0,45290472.0,297000000.0,136.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13564 entries, 0 to 13563
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_umkm                 13467 non-null  object
 1   nama_usaha              13564 non-null  object
 2   jenis_usaha             13467 non-null  object
 3   tenaga_kerja_perempuan  13444 non-null  object
 4   tenaga_kerja_laki_laki  13462 non-null  object
 5   aset                    13453 non-null  object
 6   omset                   13451 non-null  object
 7   marketplace             13447 non-null  object
 8   kapasitas_produksi      13442 non-null  object
 9   status_legalitas        13470 non-null  object
 10  tahun_berdiri           13469 non-null  object
 11  laba                    13452 non-null  object
 12  biaya_karyawan          13469 non-null  object
 13  jumlah_pelanggan        13453 non-null  object
dtypes: object(14)
memory usage: 1.4+ MB

In [4]:
df.isnull().sum()

id_umkm                    97
nama_usaha                  0
jenis_usaha                97
tenaga_kerja_perempuan    120
tenaga_kerja_laki_laki    102
aset                      111
omset                     113
marketplace               117
kapasitas_produksi        122
status_legalitas           94
tahun_berdiri              95
laba                      112
biaya_karyawan             95
jumlah_pelanggan          111
dtype: int64

In [5]:
df.describe()

,id_umkm,nama_usaha,jenis_usaha,tenaga_kerja_perempuan,tenaga_kerja_laki_laki,aset,omset,marketplace,kapasitas_produksi,status_legalitas,tahun_berdiri,laba,biaya_karyawan,jumlah_pelanggan
count,13467,13564,13467,13444,13462,13453,13451,13447,13442,13470,13469,13452,13469,13453
unique,13439,13564,8,101,101,13410,13422,6,991,3,26,13406,200,991
top,unknown,UD. Alif Pamungkas,Jasa,3,47,unknown,unknown,Website Sendiri,unknown,Terdaftar,2024,unknown,312000000,unknown
freq,29,1,3403,158,167,31,28,2758,42,6896,565,45,150,41